# Generated by Django 4.2.9 on 2024-03-21 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_alter_user_id_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_user',
        ),
        migrations.AddField(
            model_name='post',
            name='like_user',
            field=models.ManyToManyField(related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
