# Generated by Django 4.2.9 on 2024-03-21 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_like_user_post_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
