# Generated by Django 4.2.9 on 2024-04-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_user_following_followingrelationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followingrelationship',
            unique_together={('followed_user', 'following_user')},
        ),
    ]
