# Generated by Django 4.2.9 on 2024-04-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_followingrelationship_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='posted_timestamp',
        ),
    ]
