# Generated by Django 4.2.9 on 2024-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_id_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
