# Generated by Django 4.2.9 on 2024-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_auction_listing_bid_bidder_bid_bidding_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
