# Generated by Django 4.2.9 on 2024-03-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment_auction_listing_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction_listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_listing', to='auctions.auctionlisting'),
        ),
    ]
